import Link from 'next/link';
import { CodeBlock } from '@/components/site/code-block';
import { Callout } from '@/components/docs/callout';

export const metadata = {
  title: 'Error & 404 pages',
  description:
    'How JORVEL scaffolds an ErrorBoundary, a development-mode error overlay, and a default 404 page in every generated host and remote app — plus how to override them.',
};

export default function ErrorPagesDoc() {
  return (
    <>
      <h1>Error &amp; 404 pages</h1>
      <p>
        Every app generated by <code>jorvel generate host|remote</code> ships three files
        that handle runtime failure and unmatched routes. They are part of <em>your</em>{' '}
        app — not framework dependencies — so editing them is the supported customization path.
      </p>

      <Callout variant="info" title="Why ship these by default?">
        Production teams need a branded crash screen and 404 page before launch. Defaults
        cover both with sensible behavior (full stack in dev, brand-safe message in prod)
        so you can ship Day&nbsp;1 and refine later.
      </Callout>

      <h2 id="files">Scaffolded files</h2>
      <CodeBlock
        language="text"
        code={`apps/<name>/
└── src/
    ├── error-boundary.tsx     # Top-level React error boundary
    └── pages/
        ├── _error.tsx          # Crash screen — dev stack vs prod message
        ├── _404.tsx            # 404 page rendered for unknown URLs
        └── README.md           # How to override`}
      />
      <p>
        For <code>--lang js</code> apps the extensions are <code>.jsx</code> instead of{' '}
        <code>.tsx</code>; the rest is identical.
      </p>

      <h2 id="error-boundary">The error boundary</h2>
      <p>
        <code>src/error-boundary.tsx</code> is a small class component that catches{' '}
        <em>synchronous render errors</em> anywhere in the tree below it and renders the
        local <code>ErrorPage</code> from <code>pages/_error.tsx</code>. The generated
        <code> bootstrap.tsx</code> wraps the entire app in this boundary.
      </p>
      <CodeBlock
        language="tsx"
        filename="src/bootstrap.tsx"
        code={`ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <ErrorBoundary>
      <App />
    </ErrorBoundary>
  </React.StrictMode>
);`}
      />

      <h3 id="boundary-limitations">What the boundary does not catch</h3>
      <ul>
        <li>Promise rejections (async <code>fetch</code> failures, dynamic imports).</li>
        <li>Errors thrown inside event handlers.</li>
        <li>Errors during server-side rendering (caught by the SSR adapter instead).</li>
      </ul>
      <p>For unhandled promise rejections, attach a global listener:</p>
      <CodeBlock
        language="ts"
        code={`window.addEventListener('unhandledrejection', (event) => {
  // Forward to your observability sink, e.g. @jorvel/observability.
  console.error(event.reason);
});`}
      />

      <h2 id="error-page">The default error page</h2>
      <p>
        <code>pages/_error.tsx</code> renders one of two layouts based on{' '}
        <code>process.env.NODE_ENV</code>:
      </p>
      <ul>
        <li>
          <strong>Development</strong> — full <code>error.message</code> as the headline,
          formatted <code>error.stack</code> in a monospace block, dark/red theme to match
          standard dev-tools UX. A <strong>Try again</strong> button calls the{' '}
          <code>reset()</code> prop supplied by the boundary; <strong>Go home</strong>{' '}
          navigates back to <code>/</code>.
        </li>
        <li>
          <strong>Production</strong> — generic, brand-safe message (
          <em>"We hit an unexpected error"</em>), no stack, no internals. Still keeps the
          reset + go-home affordances.
        </li>
      </ul>
      <Callout variant="warn" title="Inline stack only in dev">
        Stack traces can leak server paths and module ids. JORVEL never renders them when
        <code> NODE_ENV === 'production'</code>. If you build a custom error page, preserve
        that branch.
      </Callout>

      <h2 id="not-found">The default 404 page</h2>
      <p>
        <code>pages/_404.tsx</code> exports <code>NotFoundPage</code>, which takes an
        optional <code>path</code> prop and renders a centered layout with the offending
        URL, a "go home" button, and a link back to the docs.
      </p>
      <p>
        The generated <code>bootstrap.tsx</code> includes a helper{' '}
        <code>matchesAnyHostRoute(pathname, routes)</code> that walks{' '}
        <code>jorvel.routes.host.json</code> and renders <code>NotFoundPage</code> when no
        route would handle the current URL:
      </p>
      <CodeBlock
        language="tsx"
        filename="src/bootstrap.tsx"
        code={`function App() {
  const pathname = usePathname();

  if (pathname === '/' || pathname === '') {
    return <Welcome defaultProjectName="shell" />;
  }

  if (!matchesAnyHostRoute(pathname, HOST_ROUTES)) {
    return <NotFoundPage path={pathname} />;
  }

  return <RemoteOutlet routes={HOST_ROUTES} remotes={REMOTES} />;
}`}
      />

      <h2 id="override">Override patterns</h2>

      <h3 id="override-inline">Edit the file directly</h3>
      <p>
        Both files are plain React components with zero JORVEL imports. Open{' '}
        <code>src/pages/_error.tsx</code> or <code>src/pages/_404.tsx</code> and rewrite
        the JSX. Nothing else in the framework needs to change.
      </p>

      <h3 id="override-fallback">Swap the component via boundary prop</h3>
      <p>
        Keep <code>_error.tsx</code> for the dev surface and supply a different component
        for production:
      </p>
      <CodeBlock
        language="tsx"
        code={`import { ErrorBoundary } from './error-boundary';
import { BrandedCrashScreen } from './crash-screen';

<ErrorBoundary
  fallback={process.env.NODE_ENV === 'production' ? BrandedCrashScreen : undefined}
>
  <App />
</ErrorBoundary>`}
      />

      <h3 id="override-disable">Disable the boundary</h3>
      <p>
        Remove the <code>&lt;ErrorBoundary&gt;</code> wrapper in <code>bootstrap.tsx</code>{' '}
        to fall back to React&apos;s default behavior (white screen + console error in
        production). Recommended only when you have a higher-level boundary (e.g. supplied
        by the SSR adapter) handling the same scope.
      </p>

      <h3 id="override-404">Custom 404 logic</h3>
      <p>
        The default <code>matchesAnyHostRoute</code> uses prefix matching with{' '}
        <code>/*</code> suffix support. To handle more complex matching (regex, parameter
        capture beyond <code>/*</code>), replace the helper inline or build your own and
        render <code>&lt;NotFoundPage&gt;</code> from there.
      </p>

      <h2 id="testing">Testing the pages</h2>
      <p>Throw inside any rendered component to trigger the boundary:</p>
      <CodeBlock
        language="tsx"
        code={`function BombButton() {
  return (
    <button onClick={() => { throw new Error('Manual test'); }}>
      Break the app
    </button>
  );
}`}
      />
      <p>Visit a URL that no host route handles to trigger the 404:</p>
      <CodeBlock
        language="text"
        code={`http://localhost:3000/this-path-does-not-exist`}
      />

      <h2 id="see-also">See also</h2>
      <ul>
        <li>
          <Link href="/docs/observability">Observability</Link> — wire{' '}
          <code>onError</code> + RUM beacon so caught errors land in Sentry/OTel/console.
        </li>
        <li>
          <Link href="/docs/routing">Routing</Link> — host vs remote sub-paths.
        </li>
        <li>
          <Link href="/docs/ssr">SSR</Link> — server-side error handling for{' '}
          <code>renderRouteToString</code> / <code>renderRouteToStream</code>.
        </li>
      </ul>
    </>
  );
}
