import { Command } from 'commander';
import path from 'node:path';
import fs from 'fs-extra';
import kleur from 'kleur';
import { findHostApp } from '../discovery.js';

const SW_SOURCE = `/* generated by \`jorvel sw generate\` — JORVEL offline cache */
const CACHE = 'jorvel-v1';
const REMOTE_CACHE = 'jorvel-remotes-v1';
const APP_SHELL = ['/', '/index.html'];

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((c) => c.addAll(APP_SHELL).catch(() => undefined)));
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter((k) => k !== CACHE && k !== REMOTE_CACHE).map((k) => caches.delete(k)));
    await self.clients.claim();
  })());
});

self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') self.skipWaiting();
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);

  if (/remoteEntry\\.js$/.test(url.pathname) || /\\/jorvel\\/remotes\\//.test(url.pathname)) {
    event.respondWith(staleWhileRevalidate(REMOTE_CACHE, req));
    return;
  }
  if (/\\.[a-f0-9]{8,}\\.(js|css|woff2?|png|svg|jpg|jpeg|webp)$/.test(url.pathname)) {
    event.respondWith(cacheFirst(CACHE, req));
    return;
  }
  if (req.destination === 'document' || req.headers.get('accept')?.includes('text/html')) {
    event.respondWith(networkFirst(CACHE, req));
  }
});

async function cacheFirst(name, req) {
  const cache = await caches.open(name);
  const hit = await cache.match(req);
  if (hit) return hit;
  const res = await fetch(req);
  if (res.ok) cache.put(req, res.clone());
  return res;
}

async function networkFirst(name, req) {
  const cache = await caches.open(name);
  try {
    const res = await fetch(req);
    if (res.ok) cache.put(req, res.clone());
    return res;
  } catch {
    const hit = await cache.match(req);
    if (hit) return hit;
    return cache.match('/') || Response.error();
  }
}

async function staleWhileRevalidate(name, req) {
  const cache = await caches.open(name);
  const hit = await cache.match(req);
  const fetchPromise = fetch(req).then((res) => {
    if (res.ok) cache.put(req, res.clone());
    return res;
  }).catch(() => hit);
  return hit || fetchPromise;
}
`;

export const swCommand = new Command('sw').description('Service Worker helpers (offline shell + cached remoteEntry).');

swCommand
  .command('generate')
  .description('Write jorvel-sw.js into a host app public/ folder.')
  .option('--app <name>', 'Host app folder (defaults to the discovered host app)')
  .option('--cwd <dir>', 'Workspace root', process.cwd())
  .option('--force', 'Overwrite if exists')
  .action(async (opts: { app?: string; cwd: string; force?: boolean }) => {
    const cwd = path.resolve(opts.cwd);

    // Resolve the host app folder. Explicit --app wins; otherwise discover the
    // host so we don't assume `apps/shell`.
    let appDir: string;
    let appLabel: string;
    if (opts.app) {
      appDir = path.join(cwd, 'apps', opts.app);
      appLabel = opts.app;
    } else {
      const host = await findHostApp(cwd).catch(() => null);
      if (!host) {
        console.error(kleur.red('sw: no host app found. Pass --app <name> or add a host under apps/.'));
        process.exit(1);
        return;
      }
      appDir = host.dir;
      appLabel = host.folder;
    }

    const dir = path.join(appDir, 'public');
    const target = path.join(dir, 'jorvel-sw.js');
    if (!(await fs.pathExists(appDir))) {
      console.error(kleur.red(`sw: app "${appLabel}" not found at ${path.relative(cwd, appDir)}`));
      process.exit(1);
    }
    await fs.ensureDir(dir);
    if ((await fs.pathExists(target)) && !opts.force) {
      console.log(kleur.yellow(`skip — ${path.relative(cwd, target)} exists (use --force)`));
      return;
    }
    await fs.writeFile(target, SW_SOURCE, 'utf8');
    console.log(kleur.green(`wrote ${path.relative(cwd, target)}`));
    console.log(kleur.dim('register in your bootstrap:'));
    console.log(kleur.dim(`  import { registerJorvelServiceWorker } from '@jorvel/runtime';`));
    console.log(kleur.dim(`  registerJorvelServiceWorker({ url: '/jorvel-sw.js' });`));
  });
