// THIS FILE IS AUTO-GENERATED by `jorvel routes`.
// It exposes the remote's file-based route table for the host to consume.
import type { RemotePageRoute } from '@jorvel/runtime';

export const pages: RemotePageRoute[] = [
  { path: "/_404", load: () => import("./pages/_404") },
  { path: "/_error", load: () => import("./pages/_error") },
  { path: "/index.test", load: () => import("./pages/index.test") },
  { path: "/", load: () => import("./pages/index") },
];

export default pages;
