// MF share-scope shim — AUTO-GENERATED by `jorvel generate`. Do not edit.
// Bridges Rspack federation globals to webpack-style globals so shared
// singletons resolve from the shared scope before any app code executes.
(function jorvelFederationShim() {
  const g = typeof globalThis !== 'undefined' ? globalThis
    : typeof window !== 'undefined' ? window
    : typeof self !== 'undefined' ? self : {};
  try {
    if (typeof g.__federation_init_sharing__ === 'function') {
      g.__webpack_init_sharing__ = async (scope) => g.__federation_init_sharing__(scope);
    }
    if (g.__federation_shared__) {
      const expected = g.__federation_shared__;
      if (g.__webpack_share_scopes__?.default !== expected) {
        g.__webpack_share_scopes__ = { default: expected };
      }
    }
  } catch { /* best-effort */ }
})();
