import path from 'node:path';
import fs from 'fs-extra';

/**
 * Generate `<hostDir>/src/remotes.d.ts` from the host's wiring so
 * `import('<remote>/App')` type-checks (Module Federation resolves it at
 * runtime; TS would otherwise error TS2307). The remote set is the union of
 * `jorvel.federation.json` remote keys and `jorvel.routes.host.json` route
 * `remote` fields, so it stays correct however the host was wired.
 */
export async function writeRemotesDts(
  hostDir: string,
): Promise<{ file: string; remotes: string[] }> {
  const remotes = new Set<string>();

  const fedPath = path.join(hostDir, 'jorvel.federation.json');
  if (await fs.pathExists(fedPath)) {
    try {
      const fed = (await fs.readJson(fedPath)) as { remotes?: Record<string, string> };
      for (const key of Object.keys(fed.remotes ?? {})) remotes.add(key);
    } catch {
      /* ignore malformed */
    }
  }

  const routesPath = path.join(hostDir, 'jorvel.routes.host.json');
  if (await fs.pathExists(routesPath)) {
    try {
      const r = (await fs.readJson(routesPath)) as { routes?: Array<{ remote?: string }> };
      for (const rt of r.routes ?? []) if (rt.remote) remotes.add(rt.remote);
    } catch {
      /* ignore malformed */
    }
  }

  const names = [...remotes].sort();
  const header =
    '// AUTO-GENERATED by `jorvel generate types` / `jorvel add remote`.\n' +
    '// Type declarations for Module Federation remote modules (resolved at runtime\n' +
    "// by Rspack's federation plugin).\n";
  const decls = names.map(
    (name) =>
      `declare module '${name}/App' {\n` +
      `  import type React from 'react';\n` +
      `  const RemoteApp: React.ComponentType<{ subpath?: string }>;\n` +
      `  export default RemoteApp;\n` +
      `}`,
  );

  const file = path.join(hostDir, 'src', 'remotes.d.ts');
  await fs.outputFile(file, header + '\n' + (decls.join('\n\n') || '// (no remotes wired yet)') + '\n', 'utf8');
  return { file, remotes: names };
}
